quiz_demo/quiz/Question/urls.py
from django.conf.urls import include, url
from . import views as Question_views

urlpatterns = [
    url(r'^ask_question$', Question_views.ask_question, name = 'ask_question'),
    url(r'^question_info$', Question_views.question_info, name = 'question_info'),
]

quiz_demo/quiz/User/urls.py
from django.conf.urls import include, url
from . import views as User_views

urlpatterns = [
    url(r'^login$', User_views.login, name = 'login'),
    url(r'^logout$', User_views.logout, name = 'logout'),
    url(r'^register$', User_views.register, name = 'register'),
]

quiz_demo/quiz/quiz/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from User.views import index as User_views_index
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', User_views_index, name = 'index'),
    url(r'^User/', include('User.urls')),
    url(r'^Question/', include('Question.urls')),
]

quiz_demo/quiz/Question/models.py
# -*-coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from User.models import User
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.

# @python_2_unicode_compatible
class Question(models.Model):
    author = models.ForeignKey(User, verbose_name='提问者',)
    question_text = models.TextField('问题陈述')
    number_of_answer = models.IntegerField('回答数', default=0)

    #@python2
    #def __str__(self):
    #   return self.question_text
    def __unicode__(self):
        return self.question_text

    class Meta:
        verbose_name = '问题'
        verbose_name_plural = '问题'

# @python_2_unicode_compatible
class Answer(models.Model):
    author = models.ForeignKey(User, verbose_name='回答者')
    question = models.ForeignKey(Question, verbose_name='问题')
    content = models.TextField('回答')

    # def __unicode__(self):
    #   return self.content
    def __unicode__(self):
        return self.content

    class Meta:
        verbose_name = '答案'
        verbose_name_plural = '答案'

quiz_demo/quiz/User/models.py
# -*-coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
import hashlib


# Create your models here.

def encry(password):
    p = hashlib.md5()
    p.update(password)
    return p.hexdigest()

# @python_2_unicode_compatible
class User(models.Model):
    user_name = models.CharField('用户名', max_length=200, default='')
    password = models.CharField('密码', max_length=200, default=encry('123456'), blank=True)

    # def __str__(self):
    #     return self.user_name
    def __unicode__(self):
        return self.user_name

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = '用户'

quiz_demo/quiz/Question/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse
from User.models import User
from Question.models import Question, Answer
# Create your views here.

def question_info(request):
    if request.session.get('user_name', None):
        user = User.objects.get(user_name = request.session['user_name'])
        id = request.GET.get('id', None)

        if id != None:
            question = Question.objects.get(id = id)
            if request.method == 'POST':
                answer_content = request.POST.get('answer', None)
                answer = Answer.objects.create(author = user, question = question, content = answer_content)
                answer.save()
                question.number_of_answer += 1
                question.save()
                return HttpResponseRedirect(reverse('index'))
            else:
                info = {'question': question, 'user': user}
                return render(request, 'Question/question_info.html', info)
    else:
        return HttpResponse('error')

def ask_question(request):
    if request.session.get('user_name', None):
        user = User.objects.get(user_name = request.session['user_name'])
        if request.method == 'POST':
            question_content = request.POST.get('question_content', None)
            if question_content != None:
                question = Question.objects.create(author = user, question_text = question_content)
                question.save()
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("error: 问题不能为空！")
        else:
            info = {'user': user}
            return render(request, 'Question/ask_question.html', info)
    else:
        return HttpResponseRedirect(reverse('login'))

quiz_demo/quiz/User/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse

import hashlib
from User.models import User
from Question.models import Question, Answer
# Create your views here.

def encry(password):
    p = hashlib.md5()
    p.update(password)
    return p.hexdigest()

def login(request):
    if request.method == 'POST':
        # 教程上有个get_object_or_404的用法，这里应该也可以用
        user_name = request.POST.get('user_name', None)
        password = request.POST.get('password', None)
        password = encry(password)

        try:
            user = User.objects.get(user_name = user_name, password = password)
            request.session['user_name'] = user_name
            # ?? reverse redirect
            return HttpResponseRedirect(reverse('index'))
        except:
            return HttpResponse('login error')
    else:
        return render(request, 'User/login.html')

def logout(request):
    if request.session.get('user_name', None):
        del request.session['user_name']

    return HttpResponseRedirect(reverse('login'))

def index(request):
    if request.session.get('user_name', None):# 登录过的
        user = User.objects.get(user_name = request.session['user_name'])
        question_list = Question.objects.all()
        info = {'user': user, 'question_list': question_list}
        return render(request, 'User/index.html', info)
    else:
        return HttpResponseRedirect(reverse('login'))

def register(request):
    if request.method == 'POST':
        user_name = request.POST.get('user_name')
        password = request.POST.get('password')
        password_twice = request.POST.get('password_twice')

        if password != password_twice:
            return HttpResponse("两次输入的密码不一致")
        password = encry(password)
        # 如果在user中找到了，即已经注册过的，not exist赋值true
        user, not_exist = User.objects.get_or_create(user_name = user_name, password = password)
        if not_exist:
            user.save()
            return HttpResponseRedirect(reverse('login'))
        else:
            return HttpResponse("error: 该用户已存在")
    else:
        return render(request, 'User/register.html')

quiz_demo/quiz/Question/templates/Question/ask_question.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>提问</title>
  </head>

  <body>
    <hr />
      用户: {{user.user_name}}
      <a href="{% url 'logout' %}">登出</a>
      <a href="{% url 'index' %}">首页</a>
    <hr />
    <p>问题</p>
    <form action="" method="post">
      {% csrf_token %}
      <textarea name="question_content" rows="10" cols="50"></textarea>
      <input type="submit" name="submit" value="提交">
      <input type="reset" name="reset" value="重置 ">
    </form>
</html>

quiz_demo/quiz/Question/templates/Question/question_info.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>问题详情</title>
  </head>
  <body>
    <hr>
      用户: {{user.user_name}}
      <a href="{% url 'logout' %}">登出</a>
      <a href="{% url 'index' %}">首页</a>
    <hr>
    <h1>id: {{question.id}}</h1>
    <p>
      问题: {{question.content}}
    </p>
    <hr>
    <h2> 所有回答：</h2>
    {% for answer in question.answer_set.all %}
      <h3>答案{{forloop.counter}}</h3>
      <p>回答：{{answer.content}}</p>
      <p>回答者：{{answer.author.user_name}}
    {% endfor %}
    <hr>
    <form action="" method="post">
      {% csrf_token %}
      <p>你的回答：</p>
      <textarea name="answer" rows="10" cols="50"></textarea>
      <br />
      <input type="submit" name="submit" value="提交">
      <input type="reset" name="reset" value="重置">
    </form>
  </body>
</html>

quiz_demo/quiz/User/templates/User/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>用户主页</title>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.0/jquery.js"></script>
    <script type="text/javascript" src="templates/User/index.js"></script>
  </head>

  <body>
      <hr>
        用户： {{user.user_name}}
        <a href="{% url 'ask_question' %}">提问题</a>
        <a href="{% url 'logout' %}">登出</a>
      <hr>
      <h1>question list</h1>
      {% for question in question_list %}
        <a href="{% url 'question_info' %}?id={{question.id}}">问题id: {{question.id}}</a>
          提问者: {{question.author.user_name}}<br />
          答案: {{question.number_of_answer}}<br />
          <p>内容：{{question.question_text}}</p>
        <br />
      {% endfor %}
    </body>
</html>

quiz_demo/quiz/User/templates/User/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>登录页面</title>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.0/jquery.js"></script>
    <script type="text/javascript" src="./login.js"></script>
  </head>

  <body>
    <form action="" method="post">
      <!-- 一定要加这句话！！ -->
      {% csrf_token %}
      <p> 用户名： <input type="text" name="user_name" value=""> </p>
      <p> 密码： <input type="password" name="password" value=""> </p>
      <p><input type="submit" name="submit" value="提交">
          <input type='reset' name="reset" value="重置">
      <p id="error">该用户不存在或密码不正确</p>
    </form>
    <a href="{% url 'register' %}">注册</a>
  </body>
</html>

quiz_demo/quiz/User/templates/User/register.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>注册页面</title>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.0/jquery.js"></script> -->
    <script type="text/javascript" src="./templates/User/register.js"></script>
  </head>

  <body>
    <form action="" method="post">
      <!-- 一定要加这句话！！ -->
      {% csrf_token %}
      <p> 用户名： <input type="text" name="user_name" value=""> </p>
      <p> 密码： <input type="password" name="password" value=""> </p>
      <p> 再次输入密码： <input type="password" name="password_twice" value=""> </p>
      <p><input type="submit" name="submit" value="提交">
          <input type='reset' name="reset" value="重置">
    </form>
    <a href="{% url 'login' %}">登录</a>
  </body>
</html>